version: '2'
services:
  elasticsearch-setup:
  image: adopteunops/elasticsearch-rancher-setup:latest
  stdin_open: true
  tty: true
  links:
  - elasticsearch-master:elasticsearch
  labels:
    io.rancher.container.start_once: 'true'
