version: '2'
services:
  elasticsearch-setup:
    metadata:
      templates: |
        [
          {
            "name": "mytemplate",
            "value": {
                        "template": "te*",
                        "settings": {
                          "number_of_shards": 1
                       }
                     }
          }
        ]
      repositories: |
        [
          {
            "name": "mytemplate",
            "value": {
                        "type": "fs",
                        "settings": {
                            "location": "/mount/backups/my_backup",
                            "compress": true
                        }
                      }
          }
        ]
      license: |
        #PASTE YOUR LICENSE HERE
